---
- hosts: localhost
  tasks:
    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew
    - name: Make sure homebrew is present in PATH
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root
    - name: "Install core packages via brew casks"
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: "latest"
      ignore_errors: yes
      with_items:
        - visual-studio-code
    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'curl',
          'mas',
          'openssl',
          'rust',
          'volta',
          'jetbrains-toolbox',
        ]
        state: present
        update_homebrew: yes
    - name: "Install from Mac app store"
      shell: mas install {{ item }}
      with_items:
        - 497799835 #xcode
    
